import { PrismaClient } from '@prisma/client';
import { generateULID } from '@/lib/utils/ulid.service';
import { createDateAtMidnightUTC } from '@/lib/utils/date-utils';

export async function seedHolidays(prisma: PrismaClient, generateULID: () => string, systemOrg: any) {
  // === Holidays ===
  // Create a default holiday template for Philippine holidays
  const holidayTemplate = await prisma.holidayTemplate.create({
    data: {
      id: generateULID(),
      organizationId: systemOrg.id,
      name: 'Philippine Holidays 2026',
      description: 'Default holiday template for Philippine holidays in 2026',
      isDefault: true,
    },
  });

  // Create Philippine holidays for 2026
  // Use date string and convert to UTC midnight for storage
  const holidays = [
    {
      id: generateULID(),
      name: 'Maundy Thursday',
      date: createDateAtMidnightUTC('2026-04-02'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Good Friday',
      date: createDateAtMidnightUTC('2026-04-03'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Araw ng Kagitingan',
      date: createDateAtMidnightUTC('2026-04-09'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Labor Day',
      date: createDateAtMidnightUTC('2026-05-01'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Independence Day',
      date: createDateAtMidnightUTC('2026-06-12'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Eid al-Fitr',
      date: createDateAtMidnightUTC('2026-03-31'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Eid al-Adha',
      date: createDateAtMidnightUTC('2026-06-07'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'National Heroes Day',
      date: createDateAtMidnightUTC('2026-08-31'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'All Saints\' Day',
      date: createDateAtMidnightUTC('2026-11-01'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'All Souls\' Day',
      date: createDateAtMidnightUTC('2026-11-02'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Bonifacio Day',
      date: createDateAtMidnightUTC('2026-11-30'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Christmas Eve',
      date: createDateAtMidnightUTC('2026-12-24'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Christmas Day',
      date: createDateAtMidnightUTC('2026-12-25'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Rizal Day',
      date: createDateAtMidnightUTC('2026-12-30'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
  ];

  await prisma.holiday.createMany({
    data: holidays as any,
  });

  console.log('✅ Created Philippine holidays for 2026');
}
