import { PrismaClient } from '@prisma/client';
import { generateULID } from '@/lib/utils/ulid.service';

export async function seedHolidays(prisma: PrismaClient, generateULID: () => string, systemOrg: any) {
  // === Holidays ===
  // Create a default holiday template for Philippine holidays
  const holidayTemplate = await prisma.holidayTemplate.create({
    data: {
      id: generateULID(),
      organizationId: systemOrg.id,
      name: 'Philippine Holidays 2026',
      description: 'Default holiday template for Philippine holidays in 2026',
      isDefault: true,
    },
  });

  // Create Philippine holidays for 2026
  const holidays = [
    {
      id: generateULID(),
      name: 'New Year\'s Day',
      date: new Date('2026-01-01'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Chinese Lunar New Year',
      date: new Date('2026-02-17'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'EDSA People Power Revolution Anniversary',
      date: new Date('2026-02-25'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Maundy Thursday',
      date: new Date('2026-04-17'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Good Friday',
      date: new Date('2026-04-18'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Black Saturday',
      date: new Date('2026-04-19'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Araw ng Kagitingan',
      date: new Date('2026-04-09'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Labor Day',
      date: new Date('2026-05-01'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Independence Day',
      date: new Date('2026-06-12'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Ninoy Aquino Day',
      date: new Date('2026-08-21'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'National Heroes Day',
      date: new Date('2026-08-25'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'All Saints\' Day',
      date: new Date('2026-11-01'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Bonifacio Day',
      date: new Date('2026-11-30'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Immaculate Conception',
      date: new Date('2026-12-08'),
      type: 'SPECIAL_NON_WORKING',
      rateMultiplier: 1.3,
      isPaidIfNotWorked: false,
      countsTowardOt: true,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Christmas Day',
      date: new Date('2026-12-25'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
    {
      id: generateULID(),
      name: 'Rizal Day',
      date: new Date('2026-12-30'),
      type: 'REGULAR',
      rateMultiplier: 2.0,
      isPaidIfNotWorked: true,
      countsTowardOt: false,
      organizationId: systemOrg.id,
      holidayTemplateId: holidayTemplate.id,
    },
  ];

  await prisma.holiday.createMany({
    data: holidays as any,
  });

  console.log('✅ Created Philippine holidays for 2026');
}
