import { prisma } from '@/lib/db';

/**
 * Script to cleanup payroll test data generated by generate-payroll-test-data.ts
 * Removes all test employees, their time entries, overtime requests, leave requests, payroll records,
 * and optionally the entire test organization including government contributions.
 * 
 * Usage: npx ts-node scripts/cleanup-payroll-test-data.ts [employeeEmail] [--force]
 * If no email is provided, it will clean up ALL test employees (emails ending with @testpayroll.com)
 * Use --force to delete the test organization even if it has employees
 */

async function cleanupPayrollTestData() {
  try {
    const args = process.argv.slice(2);
    const targetEmail = args[0];
    const forceCleanup = args.includes('--force');
    
    console.log('\n🧹 Starting cleanup of payroll test data...\n');
    
    // Find test employees to delete
    const whereClause = targetEmail 
      ? { email: targetEmail }
      : { email: { endsWith: '@testpayroll.com' } };
    
    const testEmployees = await prisma.employee.findMany({
      where: whereClause,
      select: {
        id: true,
        firstName: true,
        lastName: true,
        email: true,
        employeeId: true,
      }
    });
    
    if (testEmployees.length === 0) {
      console.log('✅ No test employees found to cleanup.');
      return;
    }
    
    console.log(`Found ${testEmployees.length} test employee(s) to cleanup:`);
    testEmployees.forEach(emp => {
      console.log(`  - ${emp.firstName} ${emp.lastName} (${emp.email})`);
    });
    console.log('');
    
    // Get all employee IDs
    const employeeIds = testEmployees.map(emp => emp.id);
    
    // Delete in correct order due to foreign key constraints
    
    // 1. Delete payroll earnings and deductions first
    const payrolls = await prisma.payroll.findMany({
      where: { employeeId: { in: employeeIds } },
      select: { id: true }
    });
    
    const payrollIds = payrolls.map(p => p.id);
    
    if (payrollIds.length > 0) {
      const deletedEarnings = await prisma.payrollEarning.deleteMany({
        where: { payrollId: { in: payrollIds } }
      });
      console.log(`✓ Deleted ${deletedEarnings.count} payroll earning records`);
      
      const deletedDeductions = await prisma.deduction.deleteMany({
        where: { payrollId: { in: payrollIds } }
      });
      console.log(`✓ Deleted ${deletedDeductions.count} deduction records`);
      
      const deletedPayrolls = await prisma.payroll.deleteMany({
        where: { employeeId: { in: employeeIds } }
      });
      console.log(`✓ Deleted ${deletedPayrolls.count} payroll records`);
    }
    
    // Also clean up any standalone payroll_earning records for these employees
    // First find all payroll earning records for these employees
    const allEarnings = await prisma.payrollEarning.findMany({
      where: { employeeId: { in: employeeIds } },
      select: { id: true, payrollId: true }
    });
    
    // Filter for standalone earnings (those not linked to a payroll)
    const standaloneEarningIds = allEarnings
      .filter(e => !e.payrollId)
      .map(e => e.id);
    
    if (standaloneEarningIds.length > 0) {
      const deletedStandaloneEarnings = await prisma.payrollEarning.deleteMany({
        where: { id: { in: standaloneEarningIds } }
      });
      console.log(`✓ Deleted ${deletedStandaloneEarnings.count} standalone payroll earning records`);
    }
    
    // 2. Delete time breaks
    const timeEntries = await prisma.timeEntry.findMany({
      where: { employeeId: { in: employeeIds } },
      select: { id: true }
    });
    
    const timeEntryIds = timeEntries.map(te => te.id);
    
    if (timeEntryIds.length > 0) {
      const deletedBreaks = await prisma.timeBreak.deleteMany({
        where: { timeEntryId: { in: timeEntryIds } }
      });
      console.log(`✓ Deleted ${deletedBreaks.count} time break records`);
    }
    
    // 3. Delete other related records
    const deletedOvertimes = await prisma.overtime.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedOvertimes.count} overtime records`);
    
    const deletedLeaveRequests = await prisma.leaveRequest.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedLeaveRequests.count} leave request records`);
    
    const deletedBenefits = await prisma.employeeBenefit.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedBenefits.count} employee benefit records`);
    
    const deletedDocuments = await prisma.employeeDocument.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedDocuments.count} employee document records`);
    
    const deletedCompensations = await prisma.compensation.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedCompensations.count} compensation records`);
    
    const deletedGovInfo = await prisma.employeeGovernmentInfo.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedGovInfo.count} government info records`);
    
    // 4. Delete time entries
    const deletedTimeEntries = await prisma.timeEntry.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedTimeEntries.count} time entry records`);
    
    // 5. Delete user accounts
    const deletedUsers = await prisma.user.deleteMany({
      where: { employeeId: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedUsers.count} user accounts`);
    
    // 6. Finally delete the employees
    const deletedEmployees = await prisma.employee.deleteMany({
      where: { id: { in: employeeIds } }
    });
    console.log(`✓ Deleted ${deletedEmployees.count} employee records`);
    
    // 7. Check and cleanup test organization if it has no employees
    const testOrg = await prisma.organization.findFirst({
      where: { name: 'Test Payroll Organization' },
      include: { employees: { select: { id: true } } }
    });
    
    if (testOrg && (testOrg.employees.length === 0 || forceCleanup)) {
      if (forceCleanup && testOrg.employees.length > 0) {
        console.log(`⚠️  Force deleting test organization with ${testOrg.employees.length} employees`);
      }
      // Clean up government contributions for the test organization
      console.log('🧹 Cleaning up government contributions...');
      
      const deletedTaxBrackets = await prisma.taxBracket.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedTaxBrackets.count} tax bracket records`);
      
      const deletedPhilhealth = await prisma.philhealthContribution.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedPhilhealth.count} Philhealth contribution records`);
      
      const deletedSSS = await prisma.sSSContribution.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedSSS.count} SSS contribution records`);
      
      const deletedPagibig = await prisma.pagibigContribution.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedPagibig.count} Pagibig contribution records`);
      
      // Clean up work schedules
      const deletedWorkSchedules = await prisma.workSchedule.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedWorkSchedules.count} work schedule records`);
      
      // Clean up departments and job titles
      const deletedDepartments = await prisma.department.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedDepartments.count} department records`);
      
      const deletedJobTitles = await prisma.jobTitle.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedJobTitles.count} job title records`);
      
      // Clean up late deduction policies
      const deletedLatePolicies = await prisma.lateDeductionPolicy.deleteMany({
        where: { organizationId: testOrg.id }
      });
      console.log(`✓ Deleted ${deletedLatePolicies.count} late deduction policy records`);
      
      // Finally delete the organization
      await prisma.organization.delete({
        where: { id: testOrg.id }
      });
      console.log('✓ Deleted test organization');
    } else if (testOrg) {
      console.log(`⚠️  Test organization has ${testOrg.employees.length} employees - not deleting`);
    }
    
    console.log('\n✅ Cleanup completed successfully!');
    
  } catch (error) {
    console.error('❌ Error during cleanup:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Run the cleanup
cleanupPayrollTestData();
